### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Mennaruuk** [ChanJianHao/SubMe#10]
Hello!

Thank you for your awesome work on this tool! I appreciate your social justice work.

I ran the Colab notebook, and for some reason it’s slow. I have GPU chosen in runtime settings, so there shouldn’t be a problem with performance. But it’s still comparable to performance I have on my Core i3 CPU.

Is there a way to speed up the process? Thanks a lot!

**Comment by ChanJianHao** [comment]
Hi!

That's strange. If you are running and using Google colab, things should be marginally faster. Unfortunately I am unsure of how to solve this, perhaps try testing with other runtime settings or video files/language.

All the best!
