### ISSUE TITLE
error runnig 

### ISSUE THREAD

**Issue by itsmysyntax** [ChanJianHao/SubMe#6]
how to resolve ?? i gave an one min .mp4 japense(ja) file
![image](https://user-images.githubusercontent.com/56538569/102121595-36b1a780-3e6a-11eb-9d85-e7324785bd25.png)

**Comment by ChanJianHao** [comment]
This happens at times due to issues with google translate. Could you try with another video?

**Comment by orophix** [comment]
I've tried 10 different files and run into the same problem every single time.

**Comment by ChanJianHao** [comment]
Hello, sorry I haven't had time to maintain this project. I have moved on to [Faster-Whisper](https://github.com/ChanJianHao/Faster-Whisper-Google-Colab/) which also does translation and transcribing of video files, do check it out if is what you are looking for.

If anyone has a fix for this, feel free to open a PR too.
