### ISSUE TITLE
MessageError: RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by Alalalalaki** [ChanJianHao/SubMe#8]
I am trying to 'Upload from Local' and it gives this error.

**Comment by ChanJianHao** [comment]
Hello, sorry I haven't had time to maintain this project. I have moved on to [Faster-Whisper](https://github.com/ChanJianHao/Faster-Whisper-Google-Colab/) which also does translation and transcribing of video files, do check it out if is what you are looking for.

If anyone has a fix for this, feel free to open a PR too.
